name: Build driver

permissions:
    contents: write

env:
    MESON_BUILDDIR:  "build"
    X11_PREFIX:      /home/runner/x11
    X11_BUILD_DIR:   /home/runner/build-deps

on:
    push:
    pull_request:

jobs:
    for-xserver-stable-25_0:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/build-driver
              with:
                  xserver-version: xlibre-xserver-25.0.0.5

    for-xserver-master:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/build-driver
              with:
                  xserver-version: master

    release:
        name: Release pushed tag
        runs-on: ubuntu-latest
        if: ${{ startsWith(github.ref, 'refs/tags/xlibre-') }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.ref_name }}
              run: .github/scripts/github/make-release
